name: Docker

on:
  push:
  repository_dispatch:
    types: [landsatlinks-dispatch]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_NAME: base

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build image
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          export SOURCE_DATE_EPOCH
          docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          [ "$VERSION" == "develop" ] && VERSION=dev
          echo VERSION=$VERSION
          echo DOCKER=$DOCKER_USER/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:$VERSION
          docker push $DOCKER_USER/$IMAGE_NAME:$VERSION
